config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  resources :menus
  resources :menu_items
  resources :active_menus
  resources :orders
  resources :order_items
  resources :users
  get "/user/orders/", to: "user_orders#index", as: "user_orders"
  get "/active/orders/", to: "active_orders#index", as: "active_orders"
  get "/user/completed/", to: "user_completed_orders#index", as: "completed_orders"
  get "/owner/completed/", to: "owner_completed_orders#index", as: "owner_completed_orders"
  get "/dashboard", to: "dashboard#index", as: "dashboard"
end

app/controllers/user_orders_controller.rb
class UserOrdersController < ApplicationController
  def index
  end
end

app/views/user_orders/_user-order-cart.html.erb
<table class="table  table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">&#8377; Price</th>
        <th scope="col">Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% cart_data.each do |item| %>
        <tr>
          <td ><%= item.menu_item_name %></td>
          <td><%= item.menu_item_price %></td>
          <td>
            <%= item.count %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/user_orders/index.html.erb
<h1>Your Order Details:</h1>

<div class="links-container">
    <%= link_to "Place Order", orders_path, class: "btn btn-outline-dark mr-20" %>
    <%= link_to "Completed Order", "/user/completed", class: "btn btn-outline-dark mr-20" %>
</div>

<% if @current_user.is_owner? %>
<div class="links-container">
    <%= link_to "Edit Orders", "/active/orders", class: "btn btn-outline-dark mr-20" %>
    <%= link_to "Edit Menu & Items ", "/menus", class: "btn btn-outline-dark mr-20" %>
    <%= link_to "Delivered Orders", "/owner/completed", class: "btn btn-outline-dark mr-20" %>
    <%= link_to "Dashboard", "/dashboard", class: "btn btn-outline-dark mr-20" %>
</div>
<% end %>

<h5> UserId: <%= @current_user.id %> </h5>

<% Order.get_users_active_order_ids(@current_user.id).each do |id| %>

  <%= render partial: "user-order-cart",
             locals: { cart_data: Order.find(id).order_items } %>
  <h4 class='form-label-header my-20'>Total Items: <%= Order.get_total_items_count(id) %></h4>
  <h4 class='form-label-header my-20'>Total Price: <%= Order.get_total_items_price(id) %></h4>
<% end %>