config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  resources :menus
  resources :menu_items
  resources :active_menus
  resources :orders
  resources :order_items
  resources :users
  get "/user/orders/", to: "user_orders#index", as: "user_orders"
  get "/active/orders/", to: "active_orders#index", as: "active_orders"
  get "/user/completed/", to: "user_completed_orders#index", as: "completed_orders"
  get "/owner/completed/", to: "owner_completed_orders#index", as: "owner_completed_orders"
  get "/dashboard", to: "dashboard#index", as: "dashboard"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <nav class="nav-container">
    
    <%= link_to "/orders", class: "nav-link" do %>
     <h1 class='logo-name'>
      <img src="/chef.svg" class='nav-logo'>
      Cafeman
     </h1> 
    <% end %>
    <% if @current_user %>
        <h6><%= @current_user.name %> , <%= @current_user.role %>! <h6>
        <%= link_to "Logout", destroy_session_path, method: "delete", class: "btn btn-outline-dark" %>
    <% end %>
  </nav>

   <% if flash[:error] %>
      <div  class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>

    <% if flash[:success] %>
      <div  class="alert alert-success" role="alert">
        <%= flash[:success] %>
      </div>
    <% end %>

  <body class='container'>
    <%= yield %>
  </body>
  <footer >
    2021 &copy; Cafeman
  </footer>
</html>